# permissions for end users to edit logclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logcluster-editor-role
rules:
- apiGroups:
  - operator.loggie.io
  resources:
  - logclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.loggie.io
  resources:
  - logclusters/status
  verbs:
  - get
