# permissions for end users to view logclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logcluster-viewer-role
rules:
- apiGroups:
  - operator.loggie.io
  resources:
  - logclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.loggie.io
  resources:
  - logclusters/status
  verbs:
  - get
