
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - operator.loggie.io
  resources:
  - logclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.loggie.io
  resources:
  - logclusters/finalizers
  verbs:
  - update
- apiGroups:
  - operator.loggie.io
  resources:
  - logclusters/status
  verbs:
  - get
  - patch
  - update
