apiVersion: operator.loggie.io/v1beta1
kind: LogCluster
metadata:
  name: logcluster-eventer
  namespace: loggie
spec:
  image: hub.c.163.com/loggie/loggie-operator:v1.0.0
  type: Deployment
  volumes:
    pipelineConfigDir: /etc/loggie/pipelines
    kubeletRootDir: /var/lib/kubelet
    dockerRootDir: /var/lib/docker
    hostPaths:
      - /data
  resources:
    limits:
      cpu: "8"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 100Mi
  nodeSelector:
    hostname: k8s123